### ISSUE TITLE
Visible Rule doesn't work with forward slash

### ISSUE THREAD

**Issue by MaryanneNjeri** [microsoft/azure-pipelines-task-lib#833] opened 2022-04-25 08:51 UTC
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: latest

### Issue Description
I have an input whose value is "test/value"
Eg:

{
       "name":  "abc",
       "type":  "radio",
       "label":  "Abc",
       "defaultValue":  "test1/value",
       "required":  true,
          "options":  {
                     "test1/value":  "Test 1",
                      "test2/value":  "Test 2"
                   }
              },
      "name":  "Abc2",
       "type":  "pickList",
       "label":  "Abc2",
       "defaultValue":  "test1/value",
       "required":  true,
        "visibleRule":  "abc = test1/value",
       "options":  {
                    ...
                   }
              },

Abc2 should be visible anytime abc = test1/value. But this is not the case. Kindly advise.

**Comment by alexander-smolyakov** [comment] 2022-05-23 10:24
Hey @MaryanneNjeri, let me close this ticket since the issue is not related to pipeline task SDK. Feel free to request a reopening if you have any further questions.

**Closed by alexander-smolyakov** 2022-05-23 10:24 UTC
Labels: Area: TaskLib, triage
