### ISSUE TITLE
toolrunner _argStringToArray eats up escaped quotes

### ISSUE THREAD

**Issue by saquibkhan** [microsoft/azure-pipelines-task-lib#648] opened 2020-06-24 05:49 UTC
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 

### Issue Description
toolrunner _argStringToArray eats up escaped quotes

### Expected behavior
It should no remove escaped quotes

### Actual behavior
toolrunner _argStringToArray eats up escaped quotes

### Steps to reproduce
Server - Azure Pipelines 
task DotNetCoreCLI@2
```yaml
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '-- TestRunParameters.Parameter(name=\"EdiStagingFunctionsKey\",value=\"key2\")'
``` 

**Other Inputs**

1. If we try passing quotes as a value even that is being eaten up by task-lib
Input: `-- TestRunParameters.Parameter(name=paramName,value=argwith"aquote)`
Output `-- TestRunParameters.Parameter(name=paramName,value=argwithaquote)`
2. If we use backslash then also quote is eaten up.
Input: `-- TestRunParameters.Parameter(name=paramName,value=argwith\"aquote)`
Output `-- TestRunParameters.Parameter(name=paramName,value=argwith\aquote)`

**Other Inputs:**
Input: ` -- TestRunParameters.Parameter(name=\"EdiStagingFunctionsKey\",value=\"key2\")`
Output: `TestRunParameters.Parameter(name=\EdiStagingFunctionsKey\",value=\"key2\")`
Note: Above the first escaped quotes are eaten up.

Input: `TestRunParameters.Parameter(name="EdiStagingFunctionsKey",value="key2"`
Output: `TestRunParameters.Parameter(name=EdiStagingFunctionsKey,value=key2)`

**More details on the issue from customer** - https://github.com/microsoft/azure-pipelines-tasks/issues/13130

**Our Debug analysis is as below along with the flow:**
**Issue** Bug is with azure-task-lib _argStringToArray function - https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/toolrunner.ts#L88 

**Stack-->**
https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/toolrunner.ts#L88
https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/toolrunner.ts#L838
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreCLIV2/dotnetcore.ts#L170

/cc @nohwnd @ShreyasRmsft @phanikmmsft

### Logs
```log
##[debug]C:\Program Files\dotnet\dotnet.exe arg: test
TestRunParameters.Parameter(name=\"EdiStagingFunctionsKey\",value=\"key2\")
##[debug]C:\Program Files\dotnet\dotnet.exe arg:  --logger trx --results-directory "C:\agent\_work\_temp" -- TestRunParameters.Parameter(name=\"EdiStagingFunctionsKey\",value=\"key2\")
##[debug]exec tool: C:\Program Files\dotnet\dotnet.exe
##[debug]arguments:
##[debug]   test
##[debug]   --logger
##[debug]   trx
##[debug]   --results-directory
##[debug]   C:\agent\_work\_temp
##[debug]   --
##[debug]   TestRunParameters.Parameter(name=\EdiStagingFunctionsKey",value="key2")
"C:\Program Files\dotnet\dotnet.exe" test --logger trx --results-directory C:\agent\_work\_temp -- "TestRunParameters.Parameter(name=\EdiStagingFunctionsKey\",value=\"key2\")"
##[debug]Exit code 0 received from tool 'C:\Program Files\dotnet\dotnet.exe'
##[debug]STDIO streams have closed for tool 'C:\Program Files\dotnet\dotnet.exe'
##[debug]BuildConfiguration=release
##[debug]BuildPlatform=any cpu
```

**Comment by nohwnd** [comment] 2020-09-22 10:25
Yeah, still interested in this being fixed.

**Comment by kcentralsquare** [comment] 2021-01-04 13:52
Definitely still want this resolved. Please reopen.

**Comment by kcentralsquare** [comment] 2021-01-04 13:53
I am also interested in seeing this issue resolved. Please reopen @nohwnd @saquibkhan

**Comment by kcentralsquare** [comment] 2021-01-12 14:02
Hello @nohwnd @ShreyasRmsft @phanikmmsft? This was closed over the holiday break, when I was not monitoring the email address subscribed. Definitely still need this issue resolved.

**Comment by ShreyasRmsft** [comment] 2021-01-18 14:20
@kcentralsquare could you open a new one? I am not a maintainer on this repo and do not have permissions to re-open this issue.

**Comment by mrsteamfist** [comment] 2021-01-21 18:53
I am also having the same issue:
The test run parameter argument 'TestRunParameters.Parameter(name=\\xxx", value="D:\\a\\1\\s\\out\\xxx")' is invalid. Please use the format below.
     Format: TestRunParameters.Parameter(name=\"<name>\", value=\"<value>\")
When I run:
  - task: DotNetCoreCLI@2
    displayName: Run xxx
    inputs:
      command: 'test'
      projects: '$(System.DefaultWorkingDirectory)\xxx'
      arguments: '--configuration release --framework net45 -- TestRunParameters.Parameter(name=\"xxx\", value=\"$(System.DefaultWorkingDirectory)\out\xxxx\")'

And idea when this will be fixed?

**Comment by kcentralsquare** [comment] 2021-01-21 18:59
@ShreyasRmsft I'm not a maintainer either, nor will I create a new issue just because a bot closed this one. I didn't even create this issue in the first place. Who do we have to tag to get a response from microsoft?

**Comment by ShreyasRmsft** [comment] 2021-01-21 19:49
@egor-bryzgalov could you please help re-open this issue?

**Comment by egor-bryzgalov** [comment] 2021-01-22 07:02
@ShreyasRmsft yes, sure.

**Comment by sudgarre** [comment] 2021-03-02 10:59
Any updates on this issue ?

**Comment by ALM-at-RZL** [comment] 2021-03-17 06:36
WORKAROUND
Will work with ".NET Core"-Build-Task with Command "test" on on-premise server 2019.0.1. Later not tested. But maybe...

-- "TestRunParameters.Parameter(name=\\\"<name1>\\\", value=\\\"<value1>\\\")" "TestRunParameters.Parameter(name=\\\"<name2>\\\", value=\\\"<value2>\\\")"

**Comment by ALM-at-RZL** [comment] 2021-03-20 19:07
After Update from 219.0.1 to 2020.0.1 the behavior has changed. 
Will work with ".NET Core"-Build-Task with Command "test" on on-premise server 2020.0.1

`-- "TestRunParameters.Parameter(name=\"<name1>\", value=\"<value1>\")" "TestRunParameters.Parameter(name=\"<name2>\", value=\"<value2>\")"`

**Comment by ankit-arora12** [comment] 2021-05-06 08:50
@egor-bryzgalov @damccorm There is feedback ticket open for this https://developercommunity.visualstudio.com/t/DotNetCoreCLI2-test-task-doesnt-have-ca/1370232. We tried the workaround (\, \\\) but it did not help and we were still able to reproduce the issue. Can you please provide a fix for this?

**Comment by ALM-at-RZL** [comment] 2021-05-06 10:29
The workaround above for 2019.0.1 and 2020.0.1 was running on agents in a VM with w2019-Server. Not tested on Linux-VMs - SRY

**Comment by fr4gles** [comment] 2021-06-11 07:56
We have tried multiple solutions 
- `--logger:"console;verbosity=detailed"`
- `--logger:\"console;verbosity=detailed\"`
- `"--logger:\"console;verbosity=detailed\""`
- `--logger:%22console;verbosity=detailed%22`
- `--logger:\\\"console;verbosity=detailed\\\"`
mentioned here:
- https://github.com/microsoft/azure-pipelines-tasks/issues/10712
- https://github.com/microsoft/azure-pipelines-tasks/issues/13130
with no luck

our case (job template):
```
  - task: DotNetCoreCLI@2
    displayName: ${{ format('run test {0}', parameters.testName) }}
    inputs:
      command: test
      arguments: --no-build --no-restore --verbosity $(Verbosity) --logger:"console;verbosity=detailed"
      projects: '$(ArtifactsPath)\**\$(TestName).dll'
```

**Closed** 2021-06-29 13:28 UTC
Labels: Area: TaskLib, bug
