### ISSUE TITLE
Mock Test Runner fails to download a new NodeJS distribution

### ISSUE THREAD

**Issue by ElderMael** [microsoft/azure-pipelines-task-lib#630] opened 2020-04-25 21:03 UTC
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 2.9.3

### Issue Description
While executing unit tests, when calling `MockTestRunner.run()` a binary distribution of NodeJS is being downloaded. While running on a `ubuntu-latest` agent, the download fails without any information error.

### Expected behaviour
The NodeJS binary is downloaded successfully. The test runs.

### Actual behaviour
An error is thrown during the test with the following message:
```
      Downloading file: https://nodejs.org/dist/v10.15.1/node-v10.15.1-linux-x64.tar.gz
```

### Steps to reproduce
1. Clone https://github.com/codexarcana/azure-tasks
1. Create an azure pipeline with the following code:
    ```
        npm install
        npm run test
    ```

### Logs
```bash
FAIL tests/integration.test.ts
  ● Console

    console.log
      Downloading file: https://nodejs.org/dist/v10.15.1/node-v10.15.1-linux-x64.tar.gz

      at MockTestRunner.downloadFile (node_modules/azure-pipelines-task-lib/mock-test.js:228:17)

  ● should succeed with simple inputs



       6 | 
       7 |     const testPath = path.join(__dirname, 'success.integration.js');
    >  8 |     const testMockRunner = new MockTestRunner(testPath);
         |                            ^
       9 | 
      10 |     testMockRunner.run(10);
      11 | 

      at doRequest (node_modules/sync-request/index.js:27:11)
      at MockTestRunner.downloadFile (node_modules/azure-pipelines-task-lib/mock-test.js:230:22)
      at MockTestRunner.downloadTarGz (node_modules/azure-pipelines-task-lib/mock-test.js:242:14)
      at MockTestRunner.downloadNode (node_modules/azure-pipelines-task-lib/mock-test.js:206:22)
      at MockTestRunner.getNodePath (node_modules/azure-pipelines-task-lib/mock-test.js:147:25)
      at new MockTestRunner (node_modules/azure-pipelines-task-lib/mock-test.js:28:30)
      at tests/integration.test.ts:8:28
      at step (tests/integration.test.ts:33:23)
      at Object.next (tests/integration.test.ts:14:53)
      at tests/integration.test.ts:8:71

```

**Comment by alex-peck** [comment] 2020-05-28 14:41
```
  error: Error: spawnSync /usr/local/bin/node ENOBUFS
            at Object.spawnSync (internal/child_process.js:1041:20)
            at spawnSync (child_process.js:616:24)
            at doRequest (/home/vsts/work/1/s/azure-tasks/tasks/process-template-files/node_modules/sync-request/index.js:25:13)
            at MockTestRunner.downloadFile (/home/vsts/work/1/s/azure-tasks/tasks/process-template-files/node_modules/azure-pipelines-task-lib/mock-test.js:230:22)
            at MockTestRunner.downloadTarGz (/home/vsts/work/1/s/azure-tasks/tasks/process-template-files/node_modules/azure-pipelines-task-lib/mock-test.js:242:14)
            at MockTestRunner.downloadNode (/home/vsts/work/1/s/azure-tasks/tasks/process-template-files/node_modules/azure-pipelines-task-lib/mock-test.js:206:22)
            at MockTestRunner.getNodePath (/home/vsts/work/1/s/azure-tasks/tasks/process-template-files/node_modules/azure-pipelines-task-lib/mock-test.js:147:25)
            at new MockTestRunner (/home/vsts/work/1/s/azure-tasks/tasks/process-template-files/node_modules/azure-pipelines-task-lib/mock-test.js:28:30)
            at createMockRunnerForPath (/home/vsts/work/1/s/azure-tasks/tasks/process-template-files/tests/integration.test.ts:9:28)
            at /home/vsts/work/1/s/azure-tasks/tasks/process-template-files/tests/integration.test.ts:29:28 {
          errno: 'ENOBUFS',
          code: 'ENOBUFS',
          syscall: 'spawnSync /usr/local/bin/node',
          path: '/usr/local/bin/node',
          spawnargs: [
            '/home/vsts/work/1/s/azure-tasks/tasks/process-template-files/node_modules/sync-request/lib/worker.js'
          ]
        },
```
Looks to be an issue with us using the `sync-request` library that spawns a new process. I can't seem to find a quick fix here. @stephenmichaelf

**Comment by knom** [comment] 2020-06-20 12:47
I'm using 
**azure-pipelines-task-lib version: 2.9.5**

This error comes up on Ubuntu 18 as well as Windows..

When will this be fixed?

**Comment by jo285317** [comment] 2020-06-30 05:38
I was able to fix this issue by using Node v10.18.0  as opposed to a newer version

**Comment by MichaelTsengLZ** [comment] 2020-07-09 18:42
I installed Node v10.15.1 before running `npm test` which also solved the issue. I wondering whether because AzDo build agent doesn't allow downloading anything.

**Comment by SebastianSchuetze** [comment] 2020-07-18 19:14
@MichaelTsengLZ no this issue is as well with my laptop and a Windows 10 VM within my Laptop both with full admin permission as I can see it. So it is not an agent issue.

**Comment by k32yr04n** [comment] 2020-07-20 23:30
Any fix for this yet. I'm currently facing same issue with `node v12.17.0` on Windows 10 and the following dependencies:
`"devDependencies": {
    "@types/mocha": "^8.0.0",
    "@types/node": "^14.0.23",
    "@types/q": "^1.5.4",
    "sync-request": "^6.1.0"
  }`

**Comment by MalinAan** [comment] 2020-08-17 04:09
I'm facing the same issue as well (using node v12.4.0 and azure-pipelines-task-lib 2.10.0). It seems like the problem is the buffer size to sync-request. 

I had to change line 25 in sync-request/index.js to include max buffer size to make it work.
`var res = spawnSync(process.execPath, [require.resolve('./lib/worker.js')], {input: req, maxBuffer: 50 * 1024 * 1024});`

**Comment by maxjeffos** [comment] 2020-09-08 19:29
I'm having this issue, too. In my case I'm using Node 12 and trying to upgrade from azure-pipelines-task-lib@2.9.3 to either 2.9.6 or 2.10.0. In either case, I'm getting this problem (though only in CI and not locally, for some reason - I'm using Node 12 on Mac locally and `circleci/node:lts` in CI (which appears to be Debian 9).

**Comment by jessehouwing** [comment] 2020-09-08 20:27
The agent has currently 2 versions it can run:

* Node 6 LTS, which is the version that shipped with TFS 2015u3 / TFS 2017. The 'node' execution handler will run against that node version. A custom build node binary runs with the agent.

* Node 10 LTS, which snipped some time ago. The agent will run using this node version when the execution handler of the task is set to 'node10' or when a special environment variable has been set.

Any more recent version of Node isn't guaranteed to work with the agent tasks.

Now, when you shell out to to run a node program (using Tool Runner), it will run against the version of node that's setup in the path. So it a Use Node task is in the pipeline which installs Node 12, then the task code will run in Node 6 (default) and then runs your node code using Node 12 by invoking node or npm from the path.

Hence, the mock will use one of these 2 supported node versions. And your task should target Node 6 or Node 10.

**Comment by rcomanne** [comment] 2020-12-08 09:30
Okay, this issue has me a bit puzzled.
I'm trying to test my code locally where I have Node v14 LTS installed, which is 14.15.1, but this is not working when I provide the 14 version number to my run 
`tr.run(14);`
It is because the static versions in the getNodePath function is **not** the LTS version.
Also, it will look for the NodeVersion in the task.json file. This function cleary contains a path for node14, but this is **not** allowed according to the [spec of the task.json file](https://raw.githubusercontent.com/Microsoft/azure-pipelines-task-lib/master/tasks.schema.json).
Could this be made to support more Node versions, or at least use the LTS version of Node?

This would not solve the being unable to download issue, but it will at least reduce the number of times it will have to download Node.
You could even use some regex on the node version to figure out the version instead of these static number checks....

**Comment by ganesh-kashid** [comment] 2020-12-09 17:49
Solved by following below steps to bypass the node.exe downloading

Downloaded node.exe from https://nodejs.org/dist/v10.21.0/win-x64/node.exe and saved it in home folder i.e.
"C:\Users<UserName>\azure-pipelines-task-lib_download\node10\node.exe"
Updated "<TaskName>\node_modules\azure-pipelines-task-lib\mock-test.js" and replaced function that trying to download node.exe with the path in step 1.
Updated Line: 28
Line updated: this.nodePath = getNodePath()
Line updated with: _this.nodePath = 'C:\Users\\azure-pipelines-task-lib\download\node10\node.exe';
Referred below MS Doc to install latest node and npm packages. Here I installed latest version v14.15.1, however in step1 downloaded v10.21.0 as its hardcoded in azure-pipelines-task-lib. May be azure-pipelines-task-lib is compliant with v10.21.0.
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task

**Comment by Dany-R** [comment] 2021-02-15 13:38
Nice one ganesh-kashid.  
After a bit of analyzing `mock-test.js` I found out, that (on my Win10 machine) the home directory was `c:\` where an empty directory `c:\azure-pipelines-task-lib\_download\node10\` existed (note the underscore). I copied the manually downloaded `node.exe` there and additionally created an empty file `node10.completed` in the `_download` folder (which tells the script that the download has finished successfully).  
```
c:\azure-pipelines-task-lib\_download
|   node10.completed
|
\---node10
    |    node.exe
```
Now I am able to successfully test my scripts.  

Cheers, Dany

**Comment by DaniilShmelev** [comment] 2021-04-29 08:24
Hi everyone!
The root cause of the problem is a known issue with the outdated version of sync-request (https://github.com/ForbesLindesay/sync-request/issues/81).
Updating task-lib version to latest solved the issue in @ElderMael's repository.
If updating task-lib is not an option for you, than the easiest fix would be to modify `sync-request`'s index.js inside node_modules by adding `maxBuffer: 1024 ** 4` to spawnSync options

![image](https://user-images.githubusercontent.com/72494759/116521984-50b1cb00-a8dd-11eb-8835-241e94930cd8.png)

Feel free to reopen this issue if you have any questions.

**Closed by DaniilShmelev** 2021-04-29 08:24 UTC

**Comment by martinisaksen** [comment] 2022-03-09 19:37
Another option that doesn't change any source code and mess directly with the agent is to put the following code in your `azure-pipeline.yml` file before the tests run:
_(copy directories works with Linux, but would need to change for other OS)_

```
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: "10.21.0"
  - task: CopyFiles@2
    displayName: "Copy Node to Download Directory"
    inputs:
      SourceFolder: /opt/hostedtoolcache/node/10.21.0/x64/bin
      Contents: node
      TargetFolder: /home/vsts/azure-pipelines-task-lib/_download/node10/node-v10.21.0-linux-x64/bin
  - script: echo "" > node10.completed
    displayName: Mark Node as downloaded for MockTestRunner
    workingDirectory: /home/vsts/azure-pipelines-task-lib/_download
```
