### ISSUE TITLE
Incorrect variable encoding/decoding when using setVariable + getInput

### ISSUE THREAD

**Issue by JiriKovar** [microsoft/azure-pipelines-task-lib#666] opened 2020-09-18 12:22 UTC
### Environment
azure-pipelines-task-lib version: 2.10.1

### Issue Description
When setting a variable with data that contains any of these: https://github.com/microsoft/azure-pipelines-task-lib/blob/40b976302a792bcb76454c81ee943074a0413014/node/taskcommand.ts#L93 The data gets encoded, but is not decoded upon retrieval. 

### Expected behaviour
I can retrieve the same data I stored.

### Actual behaviour
The data is encoded upon set, but is not decoded upon get. 

### Steps to reproduce
* I'm setting a secret via https://github.com/microsoft/azure-pipelines-task-lib/blob/40b976302a792bcb76454c81ee943074a0413014/node/task.ts#L161
* The secret contains JSON which contains URL with encoded query string. Please notice the %2F. Sample: 
`{
    "webhooks": [
        {
            "method": "POST",
            "url": "https://prod-83.westeurope.logic.azure.com:443/workflows/544685476486354/triggers/manual/paths/invoke?api-version=2016-06-01\u0026sp=%2Ftriggers%2Fmanual%2Frun\u0026sv=1.0\u0026sig=HEKSopljgflJUIJPjljpuipkj"
        }
    ]
}}`
* The value is later passed as input to another task and retrieved via https://github.com/microsoft/azure-pipelines-task-lib/blob/40b976302a792bcb76454c81ee943074a0413014/node/task.ts#L218 
* The retrieved value looks like this (please notice the %252F ):
`{
    "webhooks": [
        {
            "method": "POST",
            "url": "https://prod-83.westeurope.logic.azure.com:443/workflows/544685476486354/triggers/manual/paths/invoke?api-version=2016-06-01\u0026sp=%252Ftriggers%252Fmanual%252Frun\u0026sv=1.0\u0026sig=HEKSopljgflJUIJPjljpuipkj"
        }
    ]
}`
* I'm afraid that it's because of this and there is nothing I can do about it: https://github.com/microsoft/azure-pipelines-task-lib/blob/40b976302a792bcb76454c81ee943074a0413014/node/taskcommand.ts#L93

**Comment by molinch** [comment] 2020-09-28 07:34
Just got the same issue, it's really troublesome and as you said not much we can do about it

**Comment by molinch** [comment] 2020-10-09 06:54
@JiriKovar Do you have a workaround? it's screwing our secrets since % becomes %25
So currently we manually change them back, but its defeating the point of automation...

**Comment by vtbassmatt** [comment] 2020-11-06 16:27
I'm probably missing something, but I can't seem to repro this. Admittedly my attempt at a repro is simplified and that could explain it - hoping you'll spot what I'm doing wrong. I did also attempt with a secret variable which didn't seem to change anything.

```yaml
pool: { vmImage: ubuntu-latest }

steps:
- checkout: none
- script: |
    echo "##vso[task.setVariable variable=foo]sp=%2Ftriggers%2Fautomatic"
  displayName: set
- task: Bash@3
  inputs:
    targetType: inline
    script: echo $(foo)
  displayName: show
```

yields:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/714283/98390094-ef422b00-2022-11eb-90ca-0aefcdd55d66.png">

**Comment by damccorm** [comment] 2020-11-06 16:47
This should be fixed by https://github.com/microsoft/azure-pipelines-agent/pull/3152. I think the issue only manifests when you get the input via an old version of the task-lib or you don't use the task-lib at all to retrieve it

**Comment by molinch** [comment] 2020-11-09 12:23
@damccorm Could you tell us in which version of task lib the issue is solved? From what I see your PR was merged 10d ago.
![image](https://user-images.githubusercontent.com/5130190/98540758-b3130280-228e-11eb-8821-4e626fd8e832.png)

Thanks

**Comment by damccorm** [comment] 2020-11-09 21:46
@molinch that pr was on our agent repo - so it will roll out automatically. It will be turned off by default initially, but eventually fully enabled (see https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md)

**Comment by damccorm** [comment] 2020-12-14 01:32
This should be fixed

**Closed by damccorm** 2020-12-14 01:32 UTC
