### ISSUE TITLE
Cannot use JS bundler because of shelljs dependency

### ISSUE THREAD

**Issue by tjosepo** [microsoft/azure-pipelines-task-lib#942] opened 2023-05-24 21:22 UTC
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: `4.3.1`

### Issue Description
JavaScript tasks cannot be bundled using a library like `rollup` or `esbuild` because shelljs does not explicitely declare its dependencies: https://github.com/shelljs/shelljs/issues/962

There is currently a pull-request open on shelljs to address the issue, but it hasn't moved since March https://github.com/shelljs/shelljs/pull/1119

Currently, the best way I found to circumvent this is to create a bundler plugin to replace the `/node_modules/shelljs/shell.js` file with the fixed file at compile-time.

### Expected behaviour
I can bundle a task using a popular bundler like `rollup` or `esbuild` with the target platform set to `node`.

### Actual behaviour
The task will build but most shelljs files will be missing from the bundle.

There will be a runtime exception when trying to run the task due to missing dependencies that only resolve at runtime.

### Steps to reproduce
Using `esbuild`:
1. Add `esbuild` as a devDependency:
```
npm i --D esbuild
```
2. Create a `build.mjs` file with this content:
```js
import * as esbuild from 'esbuild'

await esbuild.build({
  entryPoints: ['./src/index.js'], // or whatever your entryfile is...
  outfile: './dist/index.js',
  bundle: true,
  platform: "node",
  target: "node16",
  allowOverwrite: true,
});
```
3. Run the build:
```
node build.mjs
``` 
4. Run the task:
```
node dist/index.js
```
5. An error message should appear.

### Logs
```
$ node dist/index.js
node:internal/modules/cjs/loader:1029
  throw err;
  ^

Error: Cannot find module './src/cat'
Require stack:
- /dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at /dist/index.js:2807:7
    at Array.forEach (<anonymous>)
    at node_modules/shelljs/shell.js (/dist/index.js:2806:24)
    at __require (/dist/index.js:12:52)
    at node_modules/azure-pipelines-task-lib/task.js (/dist/index.js:7287:17)
    at __require (/dist/index.js:12:52) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/dist/index.js'
  ]
}
```

**Comment by ivanduplenskikh** [comment] 2023-05-25 08:18
Hi @tjosepo thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by dnitsch** [comment] 2023-08-29 17:04
please re-activate...

**Comment by Everspace** [comment] 2023-09-18 18:47
@tjosepo I have specified a resolutions in my `package.json` since I use yarn.

```json
  "resolutions": {
    "shelljs": "Everspace/shelljs#b364c45"
  },
```

But the more correct way is

```json
{
  "dependencies": {
    "shelljs": "Everspace/shelljs#b364c45"
  },
  "overrides: {
    "shelljs": "$shelljs"
  }
```

**Comment by Everspace** [comment] 2023-12-17 19:51
not stale.

**Comment by pippolino** [comment] 2023-12-29 19:18
UP

**Comment by rbbarad** [comment] 2024-01-22 22:28
Please prioritize this issue if you can. This issue is preventing us from updating to recent versions of `azure-pipelines-task-lib`. As mentioned in the issue description, ShellJS does not plan on fixing this issue. Therefore a workaround will be needed to continue using a bundler with `azure-pipelines-task-lib`

**Comment by ivanduplenskikh** [comment] 2024-02-27 16:36
@tjosepo 
I've reproduced a problem with your example.

As a temporary solution you can use esbuild API [external option](https://esbuild.github.io/api/#external):
```js
import * as esbuild from 'esbuild'

await esbuild.build({
  entryPoints: ['./src/index.js'], // or whatever your entryfile is...
  outfile: './dist/index.js',
  bundle: true,
  platform: "node",
  target: "node16",
  allowOverwrite: true,
  external: ["shelljs"] // After adding this option the error no longer occurs
});
```

**Comment by ivanduplenskikh** [comment] 2024-02-27 17:14
Also, I found closed issue in [esbuild](https://github.com/evanw/esbuild/issues/1510) repository with a solution like as a comment above

**Comment by ivanduplenskikh** [comment] 2024-03-19 10:52
I'm closing this issue.
Feel free to reopen it if you have questions about it.

**Closed by ivanduplenskikh** 2024-03-19 10:52 UTC
Labels: Area: TaskLib

**Comment by 7PH** [comment] 2024-05-24 08:55
Hey @ivanduplenskikh , putting `shelljs` in external is not a solution that will work all the time, and when it does not, we have to provide shelljs in `node_modules` which mitigates the benefit of having a build process. Since we have a size limit for VSIX files, I would argue that this is a workaround and not a solution.

Is there any plan to address this? I see there were attempts at [dropping shelljs in the past](https://github.com/microsoft/azure-pipelines-task-lib/pull/518), for instance.

**Comment by pippolino** [comment] 2024-05-25 07:57
I tried forcing Shelljs modules. The problem is not occurring and for the moment it works.

It was used in the [dependency-check](https://github.com/dependency-check/azuredevops) for Azure DevOps library, see [commit](https://github.com/dependency-check/azuredevops/commit/6a45237c8adc2f01ca4ead61b6c9a2454d83e8f2#diff-da7f58cd94659491a9fc6ef2bf7da9eb1616ce3d081f03575eb00f8682c73da6R148-R193)

**Comment by 7PH** [comment] 2024-05-27 00:57
See [POC repository](https://github.com/7PH/azure-devops-extension-bundler-shelljs-poc), feel free to comment there if you find a better solution.

**Comment by 7PH** [comment] 2024-06-04 23:49
After further investigation, fixing `shelljs` itself is actually possible and is a better solution because it allows to use the bundled `shelljs`. I've created [an esbuild plugin](https://github.com/7PH/esbuild-plugin-shelljs) to be used as a workaround until the issue is fixe on `shelljs` side (if they decide to fix it).
