### ISSUE TITLE
Task.Json triggers validation on invisible only fields

### ISSUE THREAD

**Issue by kripajoym** [microsoft/azure-pipelines-task-lib#808] opened 2021-12-20 09:02 UTC
### Issue Description
 {
  "name": "actions",
  "type": "picklist",
  "label": "Actions",
  "defaultValue": "Select",
  "required": true,
  "helpMarkDown": "Select an Action from the dropdown as per your requirement.",
  "options": {
    "New": "Add",
    "Delete": "Delete"
  }
},

{
  "name": "backEndIPAddress",
  "type": "string",
  "label": "IP Address",
  "required": true,
  "defaultValue": "",
  "helpMarkDown": "",
  "visibleRule": "actions = New",
  "validation": {
    "expression": "isMatch(value,'^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?){0,15}$','IgnoreCase')",
    "message": "Invalid IP Address. Please try again!"
  }
} 

If the user enters a wrong value for backEndIPAddress the validation message will be displayed. this will not allow the user to save the pipeline with that error.
What if the user enters a wrong value for "backEndIPAddress", ignore that value and select the "Delete" action. 
 --- This also will not allow the user to save the pipeline. 
backEndIPAddress is a hidden field in this case. 
How can we stop validation on hidden fields?

https://stackoverflow.com/questions/52580183/task-json-triggers-validation-on-invisible-only-fields/70419314#70419314

**Comment by jessehouwing** [comment] 2021-12-20 11:26
Sounds more like a bug in Azure DevOps itself, in which case you should report it here: 
https://developercommunity.visualstudio.com/search?space=21

**Comment by max-zaytsev** [comment] 2021-12-20 21:40
@kripajoym it looks like the issue is not related to the task-lib. So close it for now. Please post this question on the dev community (see link above)

**Closed by max-zaytsev** 2021-12-20 21:40 UTC
Labels: Area: TaskLib, triage
