### ISSUE TITLE
Does TFS 2017 with agent 2.144.0 support task.setvariable?

### ISSUE THREAD

**Issue by qetza** [microsoft/azure-pipelines-task-lib#870] opened 2022-10-08 11:07 UTC
### Environment
azure-pipelines-task-lib version: 3.1.10

### Issue Description
Hello, i have a user of my task [ReplaceTokens](https://github.com/qetza/vsts-replacetokens-task) which is reporting an [issue](https://github.com/qetza/vsts-replacetokens-task/issues/281) from the `task.setvariable` command.

Is there any incompatibility between TFS2017 and the `task.setvariable`?

### Expected behaviour
The variable is set :smile:

### Actual behaviour
Error message.

### Logs
```
Unable to process command '##vso[task.setvariable variable=tokenReplacedCount;isOutput=false;issecret=false;]11' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Value cannot be null. (Parameter 'RefName')
```

**Comment by jessehouwing** [comment] 2022-10-08 12:18
Not 100% sure if TFS 2017 supported isOutput.

**Comment by ismayilov-ismayil** [comment] 2022-10-15 16:59
Hi @qetza, thanks for contribution! It seems the problem is not related with task.setvariable directly. Can you provide full log of the job?

**Comment by ismayilov-ismayil** [comment] 2022-10-27 09:44
Dear @qetza, we didn't receive update, we are closing this issue, feel free to ask any other questions or let us know if it's still relevant for you

**Closed by ismayilov-ismayil** 2022-10-27 09:44 UTC
Labels: question, Area: TaskLib
